/*
 * Sample data for Doors. Every venue, organizer and person here is invented.
 *
 * Event dates are relative so the app always has upcoming events:
 *   when: { in: n }            n days from today
 *   when: { weekday: d }       next weekday d (0 = Sunday … 6 = Saturday), today included
 * Times are 24-hour local strings and are formatted by the app.
 */
window.DOORS_DATA = {
  city: 'Chicago, IL',

  // Riso ink colors used for poster art and category markers.
  inks: {
    pink: '#FF48B0',
    blue: '#3255A4',
    sky: '#62A8E5',
    yellow: '#FFE45C',
    orange: '#FF6C2F',
    red: '#F15060',
    green: '#00A95C',
    teal: '#00838A',
    purple: '#765BA7',
    paper: '#F3EFE6',
    ink: '#1E1E28',
  },

  categories: [
    { id: 'music', label: 'Music', ink: 'pink' },
    { id: 'arts', label: 'Arts & Theater', ink: 'blue' },
    { id: 'food', label: 'Food & Drink', ink: 'orange' },
    { id: 'comedy', label: 'Comedy', ink: 'yellow' },
    { id: 'film', label: 'Film', ink: 'purple' },
    { id: 'talks', label: 'Talks', ink: 'green' },
    { id: 'sports', label: 'Sports', ink: 'teal' },
  ],

  venues: {
    foundry: { name: 'The Foundry Hall', address: '1418 W Fulton St', area: 'West Loop' },
    glasshouse: { name: 'Glasshouse Gallery', address: '2041 S Halsted St', area: 'Pilsen' },
    kinzie: { name: 'Kinzie Market Hall', address: '455 W Kinzie St', area: 'River North' },
    lakeshore: { name: 'Lakeshore Amphitheater', address: '1600 S Harbor Walk', area: 'Burnham Harbor' },
    cellar: { name: 'The Low Cellar', address: '1552 N Milwaukee Ave', area: 'Wicker Park' },
    rollerdome: { name: 'Kedzie Rollerdome', address: '3301 W Armitage Ave', area: 'Logan Square' },
    palisade: { name: 'Palisade Cinema', address: '2828 N Milwaukee Ave', area: 'Avondale' },
    midway: { name: 'Midway Lecture Hall', address: '1121 E 58th Pl', area: 'Hyde Park' },
    damen: { name: 'Damen Yards Rooftop', address: '2214 N Damen Ave', area: 'Bucktown' },
    kiln: { name: 'Kiln & Co. Studio', address: '1840 W Grand Ave', area: 'Ukrainian Village' },
    boathouse: { name: 'Riverbend Boathouse', address: '2900 S River Walk', area: 'Bridgeport' },
    cortland: { name: 'Cortland Street Works', address: '1700 W Cortland St', area: 'Bucktown' },
    signal: { name: 'Signal Hill Workshop', address: '2650 W Fulton St', area: 'East Garfield Park' },
    supper: { name: 'Southport Supper Club', address: '3159 N Southport Ave', area: 'Lakeview' },
    trailhead: { name: 'North Pier Trailhead', address: '4400 N Lakefront Trail', area: 'Uptown' },
  },

  events: [
    {
      id: 'e01',
      title: 'Night Tides',
      subtitle: 'Marisol Vega Quartet with Halden',
      cat: 'music',
      venue: 'foundry',
      when: { in: 0 },
      doors: '19:00',
      start: '20:00',
      end: '23:00',
      age: '18+',
      featured: true,
      going: 312,
      organizer: 'Foundry Live',
      desc: [
        "Marisol Vega's quartet plays the slow-burning Latin jazz from their record Night Tides, with long arrangements built around Vega's tenor sax and a two-drummer rhythm section.",
        'Chicago trio Halden opens with a short set of ambient guitar pieces. The main floor is standing room; the balcony is seated and reserved.',
      ],
      lineup: [
        { time: '20:00', name: 'Halden' },
        { time: '21:15', name: 'Marisol Vega Quartet' },
      ],
      tiers: [
        { id: 'ga', name: 'General admission', desc: 'Standing room on the main floor', price: 28, left: 140 },
        { id: 'bal', name: 'Balcony reserved', desc: 'Seated in rows A–D, assigned at the door', price: 45, left: 18 },
        { id: 'vip', name: 'Soundcheck pass', desc: 'Early entry at 6:00 PM to watch soundcheck, plus a signed LP', price: 85, left: 6 },
      ],
      good: {
        duration: '3 hours',
        access: 'Step-free entry and an accessible viewing platform',
        refunds: 'Refundable up to 48 hours before doors',
      },
      poster: { bg: 'blue', fg: 'pink', ac: 'sky', pattern: 'waves', word: 'Tides' },
    },
    {
      id: 'e16',
      title: 'Shorts on the Roof',
      subtitle: 'Nine local short films on a rooftop screen',
      cat: 'film',
      venue: 'damen',
      when: { in: 0 },
      doors: '18:30',
      start: '19:15',
      end: '21:15',
      age: 'All ages',
      going: 97,
      organizer: 'Damen Yards',
      desc: [
        'Nine short films by Chicago filmmakers, all under 15 minutes, screened on the Damen Yards rooftop with wireless headphones.',
        'Blankets and hot cider are provided. If it rains, the screening moves to the third-floor lounge.',
      ],
      lineup: [
        { time: '19:15', name: 'Program one: four shorts' },
        { time: '20:10', name: 'Program two: five shorts' },
        { time: '20:55', name: 'Filmmaker Q&A' },
      ],
      tiers: [{ id: 'roof', name: 'Rooftop seat', desc: 'Includes wireless headphones and a blanket', price: 16, left: 30 }],
      good: {
        duration: '2 hours',
        access: 'Elevator to the roof',
        refunds: 'Refundable until noon on the day',
      },
      poster: { bg: 'blue', fg: 'paper', ac: 'orange', pattern: 'halftone', word: 'Shorts' },
    },
    {
      id: 'e03',
      title: 'Late Plates Night Market',
      subtitle: '30 vendors, two bars and a late DJ set',
      cat: 'food',
      venue: 'kinzie',
      when: { in: 1 },
      start: '17:00',
      end: '23:00',
      age: 'All ages',
      featured: true,
      going: 1240,
      organizer: 'Late Plates',
      desc: [
        "Thirty of the city's night-market regulars take over Kinzie Market Hall, from hand-pulled noodles to Oaxacan tlayudas and Filipino barbecue skewers. Vendors sell small plates for $5 to $12.",
        'The tasting pass covers six plates of your choice and a drink at either bar, which works out cheaper than paying per plate if you plan to graze.',
      ],
      lineup: [
        { time: '17:00', name: 'Market opens' },
        { time: '20:00', name: 'DJ Lumen, vinyl set' },
        { time: '22:30', name: 'Last orders' },
      ],
      tiers: [
        { id: 'entry', name: 'Entry', desc: 'Entry only; buy food from the vendors', price: 12, left: 600 },
        { id: 'taste', name: 'Tasting pass', desc: 'Entry, six plates and one drink', price: 40, left: 75 },
      ],
      good: {
        duration: 'Come and go',
        access: 'Step-free throughout, with seating on both levels',
        refunds: 'Non-refundable, but transferable',
      },
      poster: { bg: 'orange', fg: 'ink', ac: 'yellow', pattern: 'sun', word: 'Plates' },
    },
    {
      id: 'e15',
      title: 'Synth Petting Zoo',
      subtitle: 'Drop in and play 30 vintage and modular synths',
      cat: 'talks',
      venue: 'signal',
      when: { in: 1 },
      start: '14:00',
      end: '17:00',
      age: 'All ages',
      going: 175,
      organizer: 'Signal Hill Workshop',
      desc: [
        'Thirty synthesizers, from 1970s analog monosynths to a wall of modular, set up with headphones so anyone can sit down and play. Staff are on hand to show you how each one works.',
        'At 4:00 PM, sound designer Ana Lisboa demonstrates how she built the sound palette for an indie game score.',
      ],
      lineup: [
        { time: '14:00', name: 'Open play' },
        { time: '16:00', name: 'Demo: Ana Lisboa' },
      ],
      tiers: [{ id: 'rsvp', name: 'Free RSVP', desc: 'Drop in any time from 2 to 5 PM', price: 0, left: 150 }],
      good: {
        duration: 'Drop in, 3 hours',
        access: 'Step-free, with seated stations',
        refunds: 'Free event',
      },
      poster: { bg: 'pink', fg: 'blue', ac: 'yellow', pattern: 'rings', word: 'Synth' },
    },
    {
      id: 'e02',
      title: 'Riso Rumble Print Fair',
      subtitle: '40 independent printers, zine makers and poster artists',
      cat: 'arts',
      venue: 'glasshouse',
      when: { weekday: 6 },
      start: '11:00',
      end: '17:00',
      age: 'All ages',
      going: 540,
      organizer: 'Pilsen Print Collective',
      desc: [
        'Forty independent risograph printers, zine makers and screen-print studios set up tables across both floors of the Glasshouse. Most prints sell for under $20, and many artists take commissions on the spot.',
        'The upstairs studio runs a hands-on two-color riso workshop every hour. Each session has 12 seats and you leave with your own print.',
      ],
      lineup: [
        { time: '11:00', name: 'Fair floor opens' },
        { time: '11:30', name: 'Two-color riso workshop, hourly' },
        { time: '15:00', name: 'Zine swap' },
      ],
      tiers: [
        { id: 'entry', name: 'Free entry', desc: 'RSVP to skip the line at the door', price: 0, left: 400 },
        { id: 'ws', name: 'Workshop seat', desc: 'One 45-minute riso workshop, materials included', price: 15, left: 11 },
      ],
      good: {
        duration: '6 hours; come and go',
        access: 'Elevator to the second floor',
        refunds: 'Workshop seats are refundable until the day before',
      },
      poster: { bg: 'yellow', fg: 'blue', ac: 'pink', pattern: 'halftone', word: 'Rumble' },
    },
    {
      id: 'e14',
      title: 'Improv Lab Showcase',
      subtitle: "The Lab's graduating class, fully improvised",
      cat: 'comedy',
      venue: 'cellar',
      when: { weekday: 6 },
      doors: '21:00',
      start: '21:30',
      end: '23:00',
      age: '21+',
      going: 64,
      organizer: 'The Low Cellar',
      desc: [
        "The Low Cellar's improv lab graduates its fall class with a fully improvised long-form show built from a single audience suggestion.",
        'Expect four teams with 20 minutes each. Shows like this run long and loose, and that is the point.',
      ],
      lineup: [
        { time: '21:30', name: 'Teams one and two' },
        { time: '22:15', name: 'Teams three and four' },
      ],
      tiers: [{ id: 'ga', name: 'General admission', desc: 'Unreserved seating', price: 12, left: 40 }],
      good: {
        duration: '90 minutes',
        access: 'Down one flight of stairs, with no elevator',
        refunds: 'Non-refundable',
      },
      poster: { bg: 'blue', fg: 'yellow', ac: 'pink', pattern: 'grid', word: 'Improv' },
    },
    {
      id: 'e04',
      title: 'Lakefront Lights Orchestra',
      subtitle: 'Film scores under the stars, with a 60-piece orchestra',
      cat: 'music',
      venue: 'lakeshore',
      when: { weekday: 0 },
      doors: '18:30',
      start: '19:30',
      end: '21:45',
      age: 'All ages',
      featured: true,
      going: 2100,
      organizer: 'Lakefront Lights',
      desc: [
        'The Lakefront Lights Orchestra closes its outdoor season with a program of film scores, from sweeping westerns to synth-era science fiction, arranged for a 60-piece orchestra and choir.',
        'Lawn tickets are general admission, so bring a blanket. Pavilion seats are numbered and covered if the weather turns.',
      ],
      lineup: [
        { time: '19:30', name: 'Part one: Frontier' },
        { time: '20:25', name: 'Intermission' },
        { time: '20:45', name: 'Part two: Orbit' },
      ],
      tiers: [
        { id: 'lawn', name: 'Lawn', desc: 'General admission; bring a blanket or a low chair', price: 35, left: 900 },
        { id: 'pav', name: 'Pavilion seat', desc: 'Covered, numbered seating', price: 65, left: 42 },
      ],
      good: {
        duration: 'About 2 hours 15 minutes, with an intermission',
        access: 'Accessible seating in pavilion row A',
        refunds: 'Full refund if cancelled for weather',
      },
      poster: { bg: 'ink', fg: 'yellow', ac: 'blue', pattern: 'rings', word: 'Lights' },
    },
    {
      id: 'e10',
      title: 'Pilsen Murals Walk',
      subtitle: 'A two-hour guided walk past 18 murals',
      cat: 'arts',
      venue: 'glasshouse',
      when: { weekday: 0 },
      start: '10:00',
      end: '12:00',
      age: 'All ages',
      going: 22,
      organizer: 'Eighteenth Street Walks',
      desc: [
        'A local muralist leads a 1.5-mile walk past 18 murals around 18th Street, with the stories behind who painted them and why. The walk starts at the Glasshouse Gallery entrance.',
        'The walk goes ahead in light rain. Wear comfortable shoes; it finishes near several cafés on 18th Street.',
      ],
      lineup: [
        { time: '10:00', name: 'Meet at the gallery entrance' },
        { time: '11:50', name: 'Walk ends on 18th Street' },
      ],
      tiers: [{ id: 'walk', name: 'Walk ticket', desc: 'Guided tour, about 1.5 miles', price: 18, left: 14 }],
      good: {
        duration: '2 hours',
        access: 'Flat route on sidewalks; some curb cuts are uneven',
        refunds: 'Full refund if cancelled for severe weather',
      },
      poster: { bg: 'red', fg: 'paper', ac: 'yellow', pattern: 'stripes', word: 'Murals' },
    },
    {
      id: 'e05',
      title: 'Tight Five Tuesdays',
      subtitle: 'Eight comics, five minutes each, one host',
      cat: 'comedy',
      venue: 'cellar',
      when: { weekday: 2 },
      doors: '19:30',
      start: '20:00',
      end: '21:30',
      age: '21+',
      going: 86,
      organizer: 'The Low Cellar',
      desc: [
        'Every Tuesday the Low Cellar books eight comics for tight five-minute sets, a mix of regulars and first-timers trying new material. Host Dee Okafor keeps it moving.',
        'There is a one-drink minimum. Seats are first come, first served, so arrive at doors if you want the front row.',
      ],
      lineup: [
        { time: '20:00', name: 'Host: Dee Okafor' },
        { time: '20:10', name: 'Eight five-minute sets' },
      ],
      tiers: [{ id: 'ga', name: 'General admission', desc: 'Unreserved seating, one-drink minimum', price: 15, left: 48 }],
      good: {
        duration: '90 minutes',
        access: 'Down one flight of stairs, with no elevator',
        refunds: 'Non-refundable',
      },
      poster: { bg: 'pink', fg: 'ink', ac: 'yellow', pattern: 'checker', word: 'Five' },
    },
    {
      id: 'e07',
      title: 'After Dark: 35mm Noir Double Bill',
      subtitle: 'Two restored crime classics, back to back',
      cat: 'film',
      venue: 'palisade',
      when: { in: 3 },
      doors: '20:30',
      start: '21:00',
      end: '00:40',
      age: '16+',
      going: 158,
      organizer: 'Palisade Cinema',
      desc: [
        'Two restored 1940s crime pictures, projected from 35mm prints on loan from a private archive. The titles are announced at the door, which is half the fun.',
        'There is a 15-minute break between features. The bar stays open, and the lobby sells popcorn with real butter.',
      ],
      lineup: [
        { time: '21:00', name: 'Feature one' },
        { time: '22:35', name: 'Intermission' },
        { time: '22:50', name: 'Feature two' },
      ],
      tiers: [
        { id: 'ga', name: 'Double bill', desc: 'Both features, unreserved seating', price: 14, left: 120 },
        { id: 'pop', name: 'Double bill and popcorn', desc: 'Both features with a large popcorn', price: 19, left: 120 },
      ],
      good: {
        duration: '3 hours 40 minutes',
        access: 'Step-free entry and a hearing loop in the auditorium',
        refunds: 'Non-refundable',
      },
      poster: { bg: 'ink', fg: 'paper', ac: 'red', pattern: 'grid', word: 'Noir' },
    },
    {
      id: 'e08',
      title: 'Cities That Breathe',
      subtitle: "Urban ecologist Dr. Priya Raman on rewilding Chicago's vacant lots",
      cat: 'talks',
      venue: 'midway',
      when: { in: 6 },
      doors: '18:00',
      start: '18:30',
      end: '20:00',
      age: 'All ages',
      going: 204,
      organizer: 'Midway Public Lectures',
      desc: [
        "Dr. Priya Raman spent three years tracking what grows, nests and pollinates on the South Side's vacant lots. She walks through the data and what it means for how the city plans green space.",
        'The talk runs 60 minutes, followed by 30 minutes of audience questions. Student tickets are free with a valid ID at the door.',
      ],
      lineup: [
        { time: '18:30', name: 'Talk: Dr. Priya Raman' },
        { time: '19:30', name: 'Audience Q&A' },
      ],
      tiers: [
        { id: 'gen', name: 'General', desc: 'Reserved seat', price: 10, left: 160 },
        { id: 'stu', name: 'Student', desc: 'Valid student ID required at the door', price: 0, left: 40 },
      ],
      good: {
        duration: '90 minutes',
        access: 'Step-free, with live captions on the main screen',
        refunds: 'Refundable until the day before',
      },
      poster: { bg: 'green', fg: 'paper', ac: 'yellow', pattern: 'rings', word: 'Breathe' },
    },
    {
      id: 'e06',
      title: 'Bruisers vs. Sirens',
      subtitle: 'Roller derby league semifinal',
      cat: 'sports',
      venue: 'rollerdome',
      when: { in: 9 },
      doors: '17:30',
      start: '18:00',
      end: '20:30',
      age: 'All ages',
      going: 430,
      organizer: 'Lakefront Derby League',
      desc: [
        'The Lakeview Bruisers and the South Side Sirens meet in the league semifinal after splitting their two regular-season bouts by a combined four points.',
        'Trackside seats are on the floor right at the rail. Bleacher seats are raised, which makes it easier to follow the whole jam.',
      ],
      lineup: [
        { time: '18:00', name: 'First half' },
        { time: '19:15', name: 'Second half' },
      ],
      tiers: [
        { id: 'bleach', name: 'Bleachers', desc: 'Unreserved raised seating', price: 22, left: 300 },
        { id: 'track', name: 'Trackside', desc: 'Floor seating at the rail, 18+ only', price: 30, left: 24 },
        { id: 'kids', name: 'Under 12', desc: 'Bleacher seat for a child with an adult', price: 8, left: 120 },
      ],
      good: {
        duration: '2.5 hours',
        access: 'Wheelchair spaces on the bleacher deck',
        refunds: 'Refundable until 7 days before',
      },
      poster: { bg: 'teal', fg: 'yellow', ac: 'blue', pattern: 'stripes', word: 'Derby' },
    },
    {
      id: 'e09',
      title: 'Open Studio: Wheel-Throwing Basics',
      subtitle: 'A three-hour beginner pottery class',
      cat: 'arts',
      venue: 'kiln',
      when: { in: 11 },
      start: '10:00',
      end: '13:00',
      age: '16+',
      going: 3,
      organizer: 'Kiln & Co.',
      desc: [
        'Learn to center, open and pull a cylinder on the wheel in a class of eight. Instructor Tomás Wierzbicki works with each student at their own pace.',
        'Clay, tools and an apron are included. Your two best pieces are glazed and fired, ready to pick up two weeks later.',
      ],
      lineup: [
        { time: '10:00', name: 'Centering and opening' },
        { time: '11:30', name: 'Pulling walls' },
        { time: '12:30', name: 'Trimming and choosing pieces' },
      ],
      tiers: [{ id: 'class', name: 'Class seat', desc: 'All materials, plus firing for two pieces', price: 48, left: 5 }],
      good: {
        duration: '3 hours',
        access: 'Ground-floor studio with step-free entry',
        refunds: 'Refundable up to 72 hours before',
      },
      poster: { bg: 'paper', fg: 'orange', ac: 'blue', pattern: 'halftone', word: 'Clay' },
    },
    {
      id: 'e13',
      title: 'Riverbend Regatta',
      subtitle: '40 crews race the 3-mile head course',
      cat: 'sports',
      venue: 'boathouse',
      when: { in: 13 },
      start: '09:00',
      end: '15:00',
      age: 'All ages',
      going: 350,
      organizer: 'Riverbend Rowing Club',
      desc: [
        'Forty college and club crews race a 3-mile head course down the South Branch, starting at 30-second intervals. The best view is at the finish line by the boathouse.',
        'Watching from the riverbank is free. Grandstand seats come with a race program and a covered seat at the finish.',
      ],
      lineup: [
        { time: '09:00', name: 'Club eights' },
        { time: '11:30', name: 'College fours' },
        { time: '14:00', name: 'Championship eights' },
      ],
      tiers: [
        { id: 'bank', name: 'Riverbank', desc: 'Free, unreserved', price: 0, left: 2000 },
        { id: 'stand', name: 'Grandstand seat', desc: 'Covered seat at the finish, with a race program', price: 20, left: 90 },
      ],
      good: {
        duration: 'Races run all day',
        access: 'Accessible viewing deck at the boathouse',
        refunds: 'Refundable if the regatta is cancelled',
      },
      poster: { bg: 'sky', fg: 'blue', ac: 'paper', pattern: 'waves', word: 'Regatta' },
    },
    {
      id: 'e11',
      title: 'Ferment Fest',
      subtitle: 'Small-batch beer, cider, kombucha and kimchi',
      cat: 'food',
      venue: 'cortland',
      when: { in: 15 },
      start: '13:00',
      end: '18:00',
      age: '21+',
      going: 610,
      organizer: 'Cortland Street Works',
      desc: [
        'Twenty-five small producers pour and plate everything fermented: farmhouse ales, dry ciders, kombucha, natto, miso and three kinds of kimchi.',
        'Your ticket includes a tasting glass and 10 pour tokens. Non-drinkers can swap tokens for food samples at any booth.',
      ],
      lineup: [
        { time: '13:00', name: 'Doors and first pours' },
        { time: '15:00', name: 'Kimchi-making demo' },
        { time: '17:30', name: 'Last pours' },
      ],
      tiers: [
        { id: 'gen', name: 'General', desc: 'Tasting glass and 10 pour tokens', price: 30, left: 220 },
        { id: 'dd', name: 'Designated driver', desc: 'Entry with food samples, no alcohol', price: 10, left: 60 },
      ],
      good: {
        duration: '5 hours',
        access: 'Step-free warehouse floor',
        refunds: 'Non-refundable, but transferable',
      },
      poster: { bg: 'yellow', fg: 'green', ac: 'orange', pattern: 'waves', word: 'Ferment' },
    },
    {
      id: 'e12',
      title: 'Halden: Album Release Show',
      subtitle: 'Halden play their second album, Low Weather, in full',
      cat: 'music',
      venue: 'foundry',
      when: { in: 20 },
      doors: '19:30',
      start: '20:30',
      end: '23:00',
      age: '18+',
      featured: true,
      going: 488,
      organizer: 'Foundry Live',
      desc: [
        'Halden play their second record, Low Weather, front to back with a string quartet, then come back for an encore of older material.',
        'Every ticket comes with a download code for the album. Vinyl preorders can be picked up at the merch table on the night.',
      ],
      lineup: [
        { time: '20:30', name: 'Saint Cecil (support)' },
        { time: '21:20', name: 'Halden' },
      ],
      tiers: [
        { id: 'ga', name: 'General admission', desc: 'Standing room, includes an album download', price: 25, left: 260 },
        { id: 'lp', name: 'General admission and vinyl', desc: 'Includes Low Weather on 12-inch vinyl', price: 48, left: 60 },
      ],
      good: {
        duration: '2.5 hours',
        access: 'Step-free entry and an accessible viewing platform',
        refunds: 'Refundable up to 48 hours before doors',
      },
      poster: { bg: 'purple', fg: 'yellow', ac: 'pink', pattern: 'sun', word: 'Halden' },
    },
    {
      id: 'e17',
      title: 'Velvet Hour Jazz Brunch',
      subtitle: 'The Ruth Adeyemi Trio and a three-course brunch',
      cat: 'music',
      venue: 'supper',
      when: { in: 23 },
      start: '11:00',
      end: '13:30',
      age: 'All ages',
      going: 70,
      organizer: 'Southport Supper Club',
      desc: [
        'The Ruth Adeyemi Trio plays two sets of standards and originals while the kitchen serves a three-course brunch.',
        'Tickets include brunch and coffee, and the menu has vegetarian and gluten-free options. Tables seat four, so smaller parties may share.',
      ],
      lineup: [
        { time: '11:15', name: 'First set' },
        { time: '12:30', name: 'Second set' },
      ],
      tiers: [{ id: 'seat', name: 'Brunch seat', desc: 'Three-course brunch and coffee', price: 38, left: 26 }],
      good: {
        duration: '2.5 hours',
        access: 'Step-free entry and restroom',
        refunds: 'Refundable up to 72 hours before',
      },
      poster: { bg: 'paper', fg: 'purple', ac: 'pink', pattern: 'sun', word: 'Brunch' },
    },
    {
      id: 'e18',
      title: 'Data & Democracy',
      subtitle: 'A panel on how election results are counted and checked',
      cat: 'talks',
      venue: 'midway',
      when: { in: 27 },
      doors: '17:30',
      start: '18:00',
      end: '19:30',
      age: 'All ages',
      going: 260,
      organizer: 'Midway Public Lectures',
      desc: [
        'A county election administrator, a statistician and a data journalist explain how ballots are counted, audited and reported on election night, and where errors actually get caught.',
        'Free with an RSVP. The panel is recorded and posted online a week later.',
      ],
      lineup: [
        { time: '18:00', name: 'Panel discussion' },
        { time: '19:00', name: 'Audience Q&A' },
      ],
      tiers: [{ id: 'rsvp', name: 'Free RSVP', desc: 'Your seat is held until 5:55 PM', price: 0, left: 180 }],
      good: {
        duration: '90 minutes',
        access: 'Step-free, with live captions',
        refunds: 'Free event',
      },
      poster: { bg: 'sky', fg: 'ink', ac: 'red', pattern: 'grid', word: 'Ballot' },
    },
    {
      id: 'e19',
      title: 'Moonlight Cabaret',
      subtitle: 'Torch songs, drag and a live five-piece band',
      cat: 'arts',
      venue: 'supper',
      when: { in: 29 },
      doors: '19:00',
      start: '20:00',
      end: '22:30',
      age: '21+',
      going: 140,
      organizer: 'Southport Supper Club',
      desc: [
        'Host Vivian Vale leads a night of torch songs, drag numbers and burlesque, backed by a live five-piece band.',
        'Cabaret tables are seated in order of booking. Dinner is available to order from 7:00 PM.',
      ],
      lineup: [
        { time: '20:00', name: 'Act one' },
        { time: '21:15', name: 'Act two' },
      ],
      tiers: [
        { id: 'bar', name: 'Bar standing', desc: 'Standing room along the bar', price: 25, left: 30 },
        { id: 'table', name: 'Cabaret table', desc: 'Seated table for the show; dinner optional', price: 55, left: 16 },
      ],
      good: {
        duration: '2.5 hours',
        access: 'Step-free entry; ask for an accessible table when booking',
        refunds: 'Refundable up to 7 days before',
      },
      poster: { bg: 'purple', fg: 'pink', ac: 'yellow', pattern: 'halftone', word: 'Cabaret' },
    },
    {
      id: 'e20',
      title: 'Lakefront Century Ride',
      subtitle: 'Supported rides of 25, 62 and 100 miles',
      cat: 'sports',
      venue: 'trailhead',
      when: { in: 35 },
      start: '07:30',
      end: '15:00',
      age: '16+',
      going: 380,
      organizer: 'North Pier Cycling',
      desc: [
        'Choose a 25-, 62- or 100-mile route along the lakefront and out through the North Shore suburbs, with marked turns and rest stops every 15 miles.',
        "Every entry includes van support, rest-stop food and a finisher's patch. Riders under 18 need a guardian's signature at check-in.",
      ],
      lineup: [
        { time: '07:30', name: 'Century riders start' },
        { time: '08:00', name: 'Metric century riders start' },
        { time: '09:00', name: '25-mile riders start' },
      ],
      tiers: [
        { id: 'r25', name: '25-mile route', desc: 'Starts at 9:00 AM', price: 40, left: 200 },
        { id: 'r62', name: 'Metric century', desc: '62 miles, starts at 8:00 AM', price: 55, left: 150 },
        { id: 'r100', name: 'Century', desc: '100 miles, starts at 7:30 AM', price: 70, left: 12 },
      ],
      good: {
        duration: 'Up to 7.5 hours',
        access: 'Adaptive and hand-cycle riders welcome on every route',
        refunds: 'Transferable until 7 days before',
      },
      poster: { bg: 'green', fg: 'yellow', ac: 'paper', pattern: 'stripes', word: 'Century' },
    },
  ],

  // Starting state for a first visit. The app stores changes in this browser.
  defaults: {
    signedIn: true,
    saved: ['e04', 'e11', 'e12'],
    orders: [],
    profile: {
      name: 'Jordan Reyes',
      email: 'jordan.reyes@example.com',
      city: 'Chicago, IL',
      since: '2024',
      attended: 14,
    },
    prefs: { favCats: ['music', 'food', 'film'], allIn: false, clock: '12' },
    notify: {
      reminders: true,
      remindWhen: '1d',
      savedUpdates: true,
      newInFavs: false,
      weekly: true,
      quiet: true,
    },
    cards: [
      { id: 'c1', brand: 'Visa', last4: '4242', exp: '08/28', label: 'Personal' },
      { id: 'c2', brand: 'Mastercard', last4: '8210', exp: '11/27', label: 'Work' },
    ],
    defaultCard: 'c1',
  },
};
